version: "3.7"

services:

  js_security:
    container_name: js_security
    image: xan/js_security_app_port3307
    ports:
      - 6666:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/?user=root

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: dockerDB
      MYSQL_ROOT_PASSWORD: root